export default {
  tags: [
    { name: 'Meeting notes' },
    { name: 'Important' },
    { name: 'Recipes' },
    { name: 'Work' },
    { name: 'Personal' },
    { name: 'Health' },
    { name: 'Fitness' },
    { name: 'Project' },
    { name: 'Ideas' },
    { name: 'Travel' },
    { name: 'Hobby' },
  ],
  folders: [
    { name: 'Personal', color: 'red' },
    { name: 'Work', color: 'blue' },
    { name: 'Notes App Project', color: 'yellow' },
    { name: 'Health & Sport', color: 'green' },
    { name: 'Hobby', color: 'magenta' },
  ],
  notes: [
    {
      title: 'Grocery List',
      folderName: 'Personal',
      tagNames: ['Personal', 'Recipes'],
      isStarred: false,
      lastUpdated: '2024-08-01',
    },
    {
      title: 'Weekly Team Meeting Agenda',
      // folderName: 'Work',
      tagNames: ['Meeting notes', 'Important'],
      isStarred: true,
      lastUpdated: '2024-08-02',
    },
    {
      title: 'My Fitness Goals for the Year',
      folderName: 'Health & Sport',
      tagNames: ['Health', 'Fitness'],
      isStarred: false,
      lastUpdated: '2024-07-25',
    },
    {
      title: 'Ideas for the Notes App Project',
      folderName: 'Notes App Project',
      tagNames: ['Project', 'Ideas'],
      isStarred: true,
      lastUpdated: '2024-07-28',
    },
    {
      title: 'Travel Packing Checklist',
      // folderName: 'Personal',
      tagNames: ['Travel', 'Personal'],
      isStarred: false,
      lastUpdated: '2024-06-15',
    },
    {
      title: 'Favorite Recipes to Try',
      // folderName: 'Personal',
      tagNames: ['Recipes', 'Important'],
      isStarred: false,
      lastUpdated: '2024-08-03',
    },
    {
      title: 'Upcoming Hobby Projects',
      folderName: 'Hobby',
      tagNames: ['Hobby', 'Ideas'],
      isStarred: false,
      lastUpdated: '2024-07-20',
    },
    {
      title: 'Work Goals for Q4',
      // folderName: 'Work',
      tagNames: ['Work', 'Important'],
      isStarred: true,
      lastUpdated: '2024-08-04',
    },
    {
      title: 'Health Tips to Follow',
      folderName: 'Health & Sport',
      tagNames: ['Health', 'Fitness'],
      isStarred: false,
      lastUpdated: '2024-07-30',
    },
    {
      title: 'Project Timeline and Milestones',
      folderName: 'Notes App Project',
      tagNames: ['Project', 'Work'],
      isStarred: true,
      lastUpdated: '2024-08-01',
    },
    {
      title: 'Top Places to Visit This Year',
      // folderName: 'Personal',
      tagNames: ['Travel', 'Ideas'],
      isStarred: false,
      lastUpdated: '2024-08-04',
    },
    {
      title: 'Book List for Summer Reading',
      folderName: 'Hobby',
      tagNames: ['Hobby'],
      isStarred: false,
      lastUpdated: '2024-07-18',
    },
    {
      title: 'Recipe for Homemade Pizza',
      folderName: 'Personal',
      tagNames: ['Recipes'],
      isStarred: false,
      lastUpdated: '2024-08-03',
    },
    {
      title:
        'Work and Life Balance Strategies for Better Productivity and Well-Being',
      // folderName: 'Work',
      tagNames: ['Work', 'Health', 'Important'],
      isStarred: true,
      lastUpdated: '2024-07-29',
    },
    {
      title: 'Crafting Ideas for the Winter Holiday Season',
      folderName: 'Hobby',
      tagNames: ['Hobby', 'Ideas'],
      isStarred: false,
      lastUpdated: '2024-08-02',
    },
    {
      title: 'Weekly Progress Report for Notes App Development',
      folderName: 'Notes App Project',
      tagNames: ['Work', 'Project', 'Important'],
      isStarred: true,
      lastUpdated: '2024-08-01',
    },
    {
      title: 'Personal Goals and Resolutions for the New Year',
      folderName: 'Personal',
      tagNames: ['Personal', 'Ideas'],
      isStarred: true,
      lastUpdated: '2024-01-01',
    },
    {
      title: 'Fitness Routine: Daily Workouts to Stay in Shape',
      folderName: 'Health & Sport',
      tagNames: ['Fitness'],
      isStarred: false,
      lastUpdated: '2024-06-01',
    },
    {
      title: 'Roadmap for Upcoming Projects and Deliverables at Work',
      folderName: 'Work',
      tagNames: ['Work', 'Project', 'Important'],
      isStarred: true,
      lastUpdated: '2024-08-04',
    },
    {
      title: 'Healthy Eating Plan and Meal Prep Ideas',
      folderName: 'Health & Sport',
      tagNames: ['Health', 'Recipes', 'Fitness'],
      isStarred: false,
      lastUpdated: '2024-08-04',
    },
  ],
};
